name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create deployment structure
        run: |
          # Create public directory
          mkdir -p public
          
          # Copy specific Python files from root
          cp interactive_quiz_game.py public/ || true
          cp password_generator.py public/ || true
          cp rock_paper_scissors_game.py public/ || true
          cp snake_game.py public/ || true
          
          # Copy README
          cp README.md public/ || true
          
          # Create and copy image_resolution_checker directory
          if [ -d "image_resolution_checker" ]; then
            mkdir -p public/image_resolution_checker
            cp image_resolution_checker/image_info.py public/image_resolution_checker/ || true
            cp image_resolution_checker/img*.{jpg,jpeg,png,gif,bmp} public/image_resolution_checker/ 2>/dev/null || true
          fi
          
          # Create and copy leetcode_analyzer directory
          if [ -d "leetcode_analyzer" ]; then
            mkdir -p public/leetcode_analyzer
            cp leetcode_analyzer/leetcode_status_analyzer.py public/leetcode_analyzer/ || true
            cp leetcode_analyzer/index.html public/leetcode_analyzer/ || true
            cp leetcode_analyzer/style.css public/leetcode_analyzer/ || true
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

