name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create deployment structure
        run: |
          mkdir -p public
          # Copy Python files from root
          cp interactive_quiz_game.py public/
          cp password_generator.py public/
          cp rock_paper_scissors_game.py public/
          cp snake_game.py public/
          # Copy README
          cp README.md public/
          
          # Copy image_resolution_checker directory
          mkdir -p public/image_resolution_checker
          cp image_resolution_checker/*.py public/image_resolution_checker/
          cp image_resolution_checker/*.{jpg,jpeg,png,gif,bmp} public/image_resolution_checker/ || true
          
          # Copy leetcode_analyzer directory
          mkdir -p public/leetcode_analyzer
          cp leetcode_analyzer/*.py public/leetcode_analyzer/
          cp leetcode_analyzer/*.html public/leetcode_analyzer/
          cp leetcode_analyzer/*.css public/leetcode_analyzer/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

